"""Pydantic schemas for Chat endpoints (PRD Section 8.3)."""

import uuid
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Request body for both POST /api/chat and POST /api/chat/stream."""

    bot_id: uuid.UUID
    session_id: str = Field(..., description="Opaque session token generated by widget client")
    message: str = Field(..., max_length=4000, description="User's chat message")


class SourceRef(BaseModel):
    """A source document reference returned with chat answers."""

    url: str
    title: Optional[str] = None


class ChatResponse(BaseModel):
    """Response for POST /api/chat (non-streaming)."""

    answer: str
    sources: List[SourceRef] = []
